/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardUsersManagementRouteImport } from './routes/dashboard/UsersManagement'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard/Orders'
import { Route as DashboardNewUserComponentRouteImport } from './routes/dashboard/NewUserComponent'
import { Route as DashboardMecanicoOrdenesRouteImport } from './routes/dashboard/MecanicoOrdenes'
import { Route as DashboardInventoryShortageRouteImport } from './routes/dashboard/InventoryShortage'
import { Route as DashboardAddFormComponentRouteImport } from './routes/dashboard/AddFormComponent'
import { Route as DashboardActivityLogsRouteImport } from './routes/dashboard/ActivityLogs'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersManagementRoute =
  DashboardUsersManagementRouteImport.update({
    id: '/UsersManagement',
    path: '/UsersManagement',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/Orders',
  path: '/Orders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNewUserComponentRoute =
  DashboardNewUserComponentRouteImport.update({
    id: '/NewUserComponent',
    path: '/NewUserComponent',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardMecanicoOrdenesRoute =
  DashboardMecanicoOrdenesRouteImport.update({
    id: '/MecanicoOrdenes',
    path: '/MecanicoOrdenes',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardInventoryShortageRoute =
  DashboardInventoryShortageRouteImport.update({
    id: '/InventoryShortage',
    path: '/InventoryShortage',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAddFormComponentRoute =
  DashboardAddFormComponentRouteImport.update({
    id: '/AddFormComponent',
    path: '/AddFormComponent',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardActivityLogsRoute = DashboardActivityLogsRouteImport.update({
  id: '/ActivityLogs',
  path: '/ActivityLogs',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/ActivityLogs': typeof DashboardActivityLogsRoute
  '/dashboard/AddFormComponent': typeof DashboardAddFormComponentRoute
  '/dashboard/InventoryShortage': typeof DashboardInventoryShortageRoute
  '/dashboard/MecanicoOrdenes': typeof DashboardMecanicoOrdenesRoute
  '/dashboard/NewUserComponent': typeof DashboardNewUserComponentRoute
  '/dashboard/Orders': typeof DashboardOrdersRoute
  '/dashboard/UsersManagement': typeof DashboardUsersManagementRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/ActivityLogs': typeof DashboardActivityLogsRoute
  '/dashboard/AddFormComponent': typeof DashboardAddFormComponentRoute
  '/dashboard/InventoryShortage': typeof DashboardInventoryShortageRoute
  '/dashboard/MecanicoOrdenes': typeof DashboardMecanicoOrdenesRoute
  '/dashboard/NewUserComponent': typeof DashboardNewUserComponentRoute
  '/dashboard/Orders': typeof DashboardOrdersRoute
  '/dashboard/UsersManagement': typeof DashboardUsersManagementRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/ActivityLogs': typeof DashboardActivityLogsRoute
  '/dashboard/AddFormComponent': typeof DashboardAddFormComponentRoute
  '/dashboard/InventoryShortage': typeof DashboardInventoryShortageRoute
  '/dashboard/MecanicoOrdenes': typeof DashboardMecanicoOrdenesRoute
  '/dashboard/NewUserComponent': typeof DashboardNewUserComponentRoute
  '/dashboard/Orders': typeof DashboardOrdersRoute
  '/dashboard/UsersManagement': typeof DashboardUsersManagementRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/ActivityLogs'
    | '/dashboard/AddFormComponent'
    | '/dashboard/InventoryShortage'
    | '/dashboard/MecanicoOrdenes'
    | '/dashboard/NewUserComponent'
    | '/dashboard/Orders'
    | '/dashboard/UsersManagement'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/ActivityLogs'
    | '/dashboard/AddFormComponent'
    | '/dashboard/InventoryShortage'
    | '/dashboard/MecanicoOrdenes'
    | '/dashboard/NewUserComponent'
    | '/dashboard/Orders'
    | '/dashboard/UsersManagement'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/ActivityLogs'
    | '/dashboard/AddFormComponent'
    | '/dashboard/InventoryShortage'
    | '/dashboard/MecanicoOrdenes'
    | '/dashboard/NewUserComponent'
    | '/dashboard/Orders'
    | '/dashboard/UsersManagement'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/UsersManagement': {
      id: '/dashboard/UsersManagement'
      path: '/UsersManagement'
      fullPath: '/dashboard/UsersManagement'
      preLoaderRoute: typeof DashboardUsersManagementRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/Orders': {
      id: '/dashboard/Orders'
      path: '/Orders'
      fullPath: '/dashboard/Orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/NewUserComponent': {
      id: '/dashboard/NewUserComponent'
      path: '/NewUserComponent'
      fullPath: '/dashboard/NewUserComponent'
      preLoaderRoute: typeof DashboardNewUserComponentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/MecanicoOrdenes': {
      id: '/dashboard/MecanicoOrdenes'
      path: '/MecanicoOrdenes'
      fullPath: '/dashboard/MecanicoOrdenes'
      preLoaderRoute: typeof DashboardMecanicoOrdenesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/InventoryShortage': {
      id: '/dashboard/InventoryShortage'
      path: '/InventoryShortage'
      fullPath: '/dashboard/InventoryShortage'
      preLoaderRoute: typeof DashboardInventoryShortageRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/AddFormComponent': {
      id: '/dashboard/AddFormComponent'
      path: '/AddFormComponent'
      fullPath: '/dashboard/AddFormComponent'
      preLoaderRoute: typeof DashboardAddFormComponentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ActivityLogs': {
      id: '/dashboard/ActivityLogs'
      path: '/ActivityLogs'
      fullPath: '/dashboard/ActivityLogs'
      preLoaderRoute: typeof DashboardActivityLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardActivityLogsRoute: typeof DashboardActivityLogsRoute
  DashboardAddFormComponentRoute: typeof DashboardAddFormComponentRoute
  DashboardInventoryShortageRoute: typeof DashboardInventoryShortageRoute
  DashboardMecanicoOrdenesRoute: typeof DashboardMecanicoOrdenesRoute
  DashboardNewUserComponentRoute: typeof DashboardNewUserComponentRoute
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardUsersManagementRoute: typeof DashboardUsersManagementRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardActivityLogsRoute: DashboardActivityLogsRoute,
  DashboardAddFormComponentRoute: DashboardAddFormComponentRoute,
  DashboardInventoryShortageRoute: DashboardInventoryShortageRoute,
  DashboardMecanicoOrdenesRoute: DashboardMecanicoOrdenesRoute,
  DashboardNewUserComponentRoute: DashboardNewUserComponentRoute,
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardUsersManagementRoute: DashboardUsersManagementRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
